events {}

http {
    server {
        listen 80;

        # Rutas del auth-service
        location /auth {
            proxy_pass http://app-auth-service:8081/auth;
        }

        # Rutas del catalog-service
        location /movies {
            proxy_pass http://app-catalog-service:8082/movies;
        }

        location /functions {
            proxy_pass http://app-catalog-service:8082/functions;
        }

        location /functionChair {
            proxy_pass http://app-catalog-service:8082/functionChair;
        }

        location /function-movie {
            proxy_pass http://app-catalog-service:8082/function-movie;
        }

        # Rutas del booking-service
        location /reservation {
            proxy_pass http://app-booking-service:8083/reservation;
        }

        location /payments {
            proxy_pass http://app-booking-service:8083/payments;
        }
    }
}